DROP TABLE if exists CLIENT;
DROP TABLE if exists LOGIN;

create table CLIENT (ID bigint generated by default as identity, BALANCE bigint, NAME varchar(255) not null, login_ID bigint, primary key (ID));
create table LOGIN (ID bigint generated by default as identity, ACCOUNT varchar(255), PASSWORD varchar(255), primary key (ID));
alter table CLIENT add constraint FKa3ssc0nqdut7314v6bopp79s6 foreign key (login_ID) references LOGIN;

insert into login(id, account, password) values(1, '123', '123');
insert into client(balance, name, login_id ) values(1000, 'Welisson Oliveira', 1);
insert into login(id, account, password) values(2, 'ABC', 'ABC');
insert into client(balance, name, login_id ) values(1000, 'User 2', 2);
