create table CLIENT (ID bigint generated by default as identity, BALANCE bigint, NAME varchar(255) not null, login_ID bigint, primary key (ID));
create table LOGIN (ID bigint generated by default as identity, ACCOUNT varchar(255), PASSWORD varchar(255), primary key (ID));
alter table CLIENT add constraint FKa3ssc0nqdut7314v6bopp79s6 foreign key (login_ID) references LOGIN;


--create table login (id BIGINT , account VARCHAR(255), password VARCHAR(255) );
--create table client (id BIGINT , name VARCHAR(255) , balance BIGINT , login_id BIGINT references login(id));